# Generated by Django 3.2 on 2023-05-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_auto_20230424_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='powergrid',
            name='reward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
